version: "3.5"

services:
  grafana:
    name: grafana-diagram
    image: grafana/grafana:7.4.0
    ports:
    - "3000:3000"
    volumes:
    - ./dist:/var/lib/grafana/plugins/jdbranham-diagram-panel
    - ./data:/var/lib/grafana
    environment:
    - TERM=linux
